---
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps
  rebase-strategy: auto
  ignore:
  - dependency-name: vue
    versions:
    - 3.5.42
  - dependency-name: vue-router
    versions:
    - 5.3.0
  - dependency-name: vite
    versions:
    - 8.2.2
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: actions
  rebase-strategy: auto
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
